PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?resource

WHERE {
  ?resource rdfs:label ?label .
  ?resource2 rdfs:label ?label .
  FILTER (?resource != ?resource2)
}
