/* docs/sw.js */
/* Offline-first-ish SW:
   - app/documents/assets: network-first
   - graph.jsonld: stale-while-revalidate
*/

const SW_VERSION = 'reasonlynx-monorepo-v12';
const CACHE_SHELL = `ontoeagle-shell-${SW_VERSION}`;
const CACHE_DATA = `ontoeagle-data-${SW_VERSION}`;

// Keep this list tight and explicit.
const SHELL_ASSETS = [
  './vendor/jszip-esm.js',
  './vendor/jszip.min.js',
  './vendor/xlsx.full.min.js',
  './vendor/glide-data-grid.min.js',
  './app/root-service-worker.js',
  './tabular-ontology-maker/favicon.ico',
  './tabular-ontology-maker/favicon.svg',
  './tabular-ontology-maker/manifest.json',
  './tabular-ontology-maker/template.xlsx',
  './tabular-ontology-maker/template.csv',
  './tabular-ontology-maker/json/bfo-cco-lookup.json',
  './tabular-ontology-maker/json/bfo-lookup.json',
  './tabular-ontology-maker/json/cco-lookup.json',
  './tabular-ontology-maker/styles/tom-axiom-builder.css',
  './tabular-ontology-maker/styles/ontology_spreadsheet_styles.css',
  './vendor/glide-data-grid.min.css',
  './tabular-ontology-maker/app/tom-ui.js',
  './tabular-ontology-maker/app/tom-project-storage.js',
  './tabular-ontology-maker/app/tom-grid-glide.js',
  './tabular-ontology-maker/app/tom-feature-utils.js',
  './tabular-ontology-maker/app/tom-core.js',
  './tabular-ontology-maker/app/tom-core-utils.js',
  './tabular-ontology-maker/app/tom-axiom-builder.js',
  './tabular-ontology-maker/app/tom-app.js',
  './tabular-ontology-maker/app/build-info.js',
  './tabular-ontology-maker/',
  './about/',
  './admin/',
  './bundler/',
  './cq-ferret/',
  './onto-eagle/',
  './ontology-viewer/',
  './styles/app-base.css',
  './styles/bundler.css',
  './styles/ontology-pages.css',
  './styles/search-app.css',
  './styles/site-header.css',
  './styles/skeleton.css',
  './styles/tabulator.min.css',
  './app/catalog-data-manager.js',
  './cq-ferret/cq-ferret-indexeddb-store.js',
  './onto-eagle/namespaces.js',
  './onto-eagle/normalize.js',
  './app/ontoeagle-indexeddb-store.js',
  './app/ontology-icons.js',
  './app/ontology-meta.js',
  './app/rdf_extract.js',
  './app/site-header.js',
  './bundler/slim-core.js',
  './app/types.js',
  './cq-ferret/vocab-extract-core.js',
  './bundler/bundler-core.js',
  './bundler/bundler-ui.js',
  './cq-ferret/extracted-vocabulary-tabulator.js',
  './cq-ferret/ferret.js',
  './onto-eagle/ontology-catalog.js',
  './onto-eagle/search-main.js',
  './onto-eagle/search.js',
  './ontology-viewer/ontology-viewer.js',
  './packages/browser-file-io/src/create-accept-attribute.js',
  './packages/browser-file-io/src/create-text-blob.js',
  './packages/browser-file-io/src/download-blob.js',
  './packages/browser-file-io/src/download-text-file.js',
  './packages/browser-file-io/src/filename-utils.js',
  './packages/browser-file-io/src/index.js',
  './packages/browser-file-io/src/read-file-as-array-buffer.js',
  './packages/browser-file-io/src/read-file-as-text.js',
  './packages/format-registry/src/index.js',
  './packages/format-registry/src/mime-registry.js',
  './packages/format-registry/src/rdf-content-detection.js',
  './packages/format-registry/src/rdf-parser-formats.js',
  './packages/indexeddb-data-management/src/file-system-access.js',
  './packages/indexeddb-data-management/src/graph-operations.js',
  './packages/indexeddb-data-management/src/id-generation.js',
  './packages/indexeddb-data-management/src/index.js',
  './packages/indexeddb-data-management/src/indexeddb-adapter.js',
  './packages/indexeddb-data-management/src/legacy-migration.js',
  './packages/indexeddb-data-management/src/project-export.js',
  './packages/indexeddb-data-management/src/project-file-locks.js',
  './packages/indexeddb-data-management/src/project-file-paths.js',
  './packages/indexeddb-data-management/src/project-folder-handle-store.js',
  './packages/indexeddb-data-management/src/project-folder-sync.js',
  './packages/indexeddb-data-management/src/project-manifest.js',
  './packages/indexeddb-data-management/src/project-portfolio-store.js',
  './packages/indexeddb-data-management/src/rdfjs-quad-rows.js',
  './packages/indexeddb-data-management/src/record-jsonld.js',
  './packages/indexeddb-data-management/src/record-store.js',
  './packages/indexeddb-data-management/src/records.js',
  './packages/indexeddb-data-management/src/run-output-export.js',
  './packages/indexeddb-data-management/src/storage-error.js',
  './packages/namespace-registry/src/curie.js',
  './packages/namespace-registry/src/index.js',
  './packages/namespace-registry/src/namespace-registry.js',
  './packages/namespace-registry/src/namespace-stems.js',
  './packages/namespace-registry/src/prefix-map.js',
  './packages/namespace-registry/src/rdf-prefixes.js',
  './packages/namespace-registry/src/rdf-serialization-prefixes.js',
  './packages/normalization-utils/src/case-conversion.js',
  './packages/normalization-utils/src/date-parts.js',
  './packages/normalization-utils/src/filename-timestamps.js',
  './packages/normalization-utils/src/index.js',
  './packages/ontology-metadata/src/import-target.js',
  './packages/ontology-metadata/src/index.js',
  './packages/ontology-metadata/src/jsonld-metadata.js',
  './packages/ontology-metadata/src/rdf-metadata.js',
  './packages/ontology-metadata/src/settings.js',
  './packages/ontology-utils/src/identifiers.js',
  './packages/ontology-utils/src/index.js',
  './packages/ontology-utils/src/iri.js',
  './packages/ontology-utils/src/ontology-input.js',
  './packages/ontology-utils/src/ontology-namespace.js',
  './packages/ontology-utils/src/rdf-terms.js',
  './packages/ontology-utils/src/xsd-datatypes.js',
  './packages/rdf-io/src/graph-export.js',
  './packages/rdf-io/src/index.js',
  './packages/rdf-io/src/jsonld-adapter.js',
  './packages/rdf-io/src/n3-adapter.js',
  './packages/rdf-io/src/object-to-rdf.js',
  './packages/rdf-io/src/rdf-model.js',
  './packages/rdf-io/src/rdflib-adapter.js',
  './packages/rdf-io/src/runtime.js',
  './packages/rdf-io/src/serialize-rdf.js',
  './packages/report-export/src/export-descriptor.js',
  './packages/report-export/src/html-document.js',
  './packages/report-export/src/index.js',
  './packages/report-export/src/print-document.js',
  './packages/report-export/src/report-error.js',
  './packages/report-export/src/yaml-document.js',
  './packages/sparql-utils/src/index.js',
  './packages/sparql-utils/src/iri-rewrite.js',
  './packages/sparql-utils/src/lexical-scan.js',
  './packages/sparql-utils/src/prologue.js',
  './packages/sparql-utils/src/query-kind.js',
  './packages/sparql-utils/src/query-patterns.js',
  './packages/sparql-utils/src/update-patterns.js',
  './packages/tabular-io/src/delimited-text.js',
  './packages/tabular-io/src/index.js',
  './packages/tabular-io/src/iri-mapping.js',
  './packages/tabular-io/src/query-records.js',
  './packages/tabular-io/src/table-shape.js',
  './packages/ui-feedback/src/feedback-error.js',
  './packages/ui-feedback/src/index.js',
  './packages/ui-feedback/src/logger.js',
  './packages/ui-feedback/src/status.js',
  './packages/ui-feedback/src/theme.js',
  './packages/ui-feedback/src/toast.js',
  './vendor/jsonld.min.js',
  './vendor/mermaid.min.js',
  './vendor/n3.min.js',
  './vendor/rdflib.min.js',
  './vendor/tabulator.min.js',
  './images/add-to-cart.svg',
  './images/block-logo.png',
  './images/default-logo.png',
  './axiolotl/',
  './axiolotl/app/axiolotl-inference.js',
  './axiolotl/app/axiolotl-inference.test.js',
  './axiolotl/app/axiolotl-query.js',
  './axiolotl/app/axiolotl-workspace-export.js',
  './axiolotl/app/axiolotl-workspace-export.test.js',
  './axiolotl/app/comunica-indexeddb-bridge.js',
  './axiolotl/app/indexeddb-triplestore.js',
  './axiolotl/app/indexeddb-triplestore.test.js',
  './axiolotl/app/jest.config.mjs',
  './axiolotl/app/mock-executor.js',
  './axiolotl/app/pipeline-registry.js',
  './axiolotl/app/pipeline-runner.js',
  './axiolotl/app/pipeline-validate.js',
  './axiolotl/app/query-registry.js',
  './axiolotl/app/semantic-core.js',
  './axiolotl/app/sparql-pattern-visualizer/constants.js',
  './axiolotl/app/sparql-pattern-visualizer/log.js',
  './axiolotl/app/sparql-ui.js',
  './axiolotl/app/sparql-utils.test.js',
  './axiolotl/app/workflow-model.js',
  './axiolotl/images/Screenshot 2025-09-20 055814.png',
  './axiolotl/images/Screenshot 2025-09-20 060644.png',
  './axiolotl/images/Screenshot 2025-09-20 060723.png',
  './axiolotl/images/axiolotl-icon.png',
  './axiolotl/images/axiolotl-white-alt.svg',
  './axiolotl/images/axiolotl-white-mini.svg',
  './axiolotl/images/axiolotl-white.svg',
  './axiolotl/images/axiolotl.svg',
  './axiolotl/images/axiolotl_raw-5-white.png',
  './axiolotl/images/axiolotl_raw-5.png',
  './axiolotl/images/axiolotl_raw-6-white.png',
  './axiolotl/index.html',
  './axiolotl/ontology-files/AgentOntology.ttl',
  './axiolotl/ontology-files/InformationEntityOntology.ttl',
  './axiolotl/ontology-files/bfo-core.ttl',
  './axiolotl/ontology-files/dcat3.ttl',
  './axiolotl/ontology-files/foaf-20140114.rdf',
  './axiolotl/ontology-files/geojson.rdf',
  './axiolotl/ontology-files/ingest.txt',
  './axiolotl/ontology-files/iri-mapping-v2.0.csv',
  './axiolotl/ontology-files/omo.owl',
  './axiolotl/ontology-files/ontology-list.json',
  './axiolotl/ontology-files/owl.ttl',
  './axiolotl/ontology-files/rdf-schema.ttl',
  './axiolotl/ontology-files/rdf-syntax.ttl',
  './axiolotl/ontology-files/skos.rdf',
  './axiolotl/ontology-files/vcard',
  './axiolotl/query-pipelines/example-workflow.json',
  './axiolotl/query-pipelines/pipelines.manifest.json',
  './axiolotl/sparql-queries/all-triples-from-default-and-named-graphs.rq',
  './axiolotl/sparql-queries/all-triples-from-named-graphs.rq',
  './axiolotl/sparql-queries/avoid-punning.rq',
  './axiolotl/sparql-queries/infer-domain.rq',
  './axiolotl/sparql-queries/infer-inverse.rq',
  './axiolotl/sparql-queries/infer-range.rq',
  './axiolotl/sparql-queries/infer-subclassof.rq',
  './axiolotl/sparql-queries/infer-subpropertyof.rq',
  './axiolotl/sparql-queries/infer-symmetric.rq',
  './axiolotl/sparql-queries/infer-transitive.rq',
  './axiolotl/sparql-queries/iri-mapping-template.csv',
  './axiolotl/sparql-queries/ontology-metadata.rq',
  './axiolotl/sparql-queries/ontology-tabulator.rq',
  './axiolotl/sparql-queries/q_class-missing-skos-definition.rq',
  './axiolotl/sparql-queries/q_ontology-has-dcterms-license-with-cc0-or-ccby3-or-higher-URL.rq',
  './axiolotl/sparql-queries/queries.manifest.json',
  './axiolotl/styles/axiolotl.css',
  './axiolotl/styles/sviz.css',
  './graph-analyst-playbook/',
  './graph-analyst-playbook/index.html',
  './graph-analyst-playbook/analyst-workflow.html',
  './graph-analyst-playbook/app/analyst-workflow.js',
  './graph-analyst-playbook/app/playbook-builder-main.js',
  './graph-analyst-playbook/styles/analyst-workflow.css',
  './graph-analyst-playbook/styles/playbook.css',
  './graph-analytics/',
  './graph-analytics/index.html',
  './graph-analytics/app/graph-analytics.js',
  './graph-analytics/app/path-finder.js',
  './graph-analytics/styles/graph-analytics.css',
  './iri-swapper/',
  './iri-swapper/app/iri-swapper-run-store.js',
  './iri-swapper/app/ont-iri-swapper.js',
  './iri-swapper/app/sparql-iri-swapper.js',
  './iri-swapper/examples/bfo-core.ttl',
  './iri-swapper/examples/example-mapping-sparql.csv',
  './iri-swapper/examples/example-mapping.csv',
  './iri-swapper/examples/example-mapping.tsv',
  './iri-swapper/examples/mapping.csv',
  './iri-swapper/examples/mapping.ods',
  './iri-swapper/examples/mapping.xlsx',
  './iri-swapper/examples/q_annotationproperty-missing-rdfs-label.rq',
  './iri-swapper/examples/q_annotationproperty-missing-skos-definition.rq',
  './iri-swapper/icon.svg',
  './iri-swapper/images/myna-iri-swapper-alt.svg',
  './iri-swapper/index.html',
  './iri-swapper/manifest.webmanifest',
  './iri-swapper/sparql-iri-swapper.html',
  './iri-swapper/styles/iri-swapper.css',
  './iri-swapper/sw.js',
  './iri-swapper/vendor.manifest.json',
  './ontology-compliance-diagnostic/',
  './ontology-compliance-diagnostic/Violations.ttl',
  './ontology-compliance-diagnostic/app/criteria.js',
  './ontology-compliance-diagnostic/app/data/nlp-qa-english-lexicon.js',
  './ontology-compliance-diagnostic/app/edit-session.js',
  './ontology-compliance-diagnostic/app/engine.js',
  './ontology-compliance-diagnostic/app/grader.js',
  './ontology-compliance-diagnostic/app/main.js',
  './ontology-compliance-diagnostic/app/measures-export.js',
  './ontology-compliance-diagnostic/app/measures-main.js',
  './ontology-compliance-diagnostic/app/measures-model.js',
  './ontology-compliance-diagnostic/app/nlp-qa-main.js',
  './ontology-compliance-diagnostic/app/nlp-qa-model.js',
  './ontology-compliance-diagnostic/app/nlp-qa-ontology.js',
  './ontology-compliance-diagnostic/app/nlp-qa-storage.js',
  './ontology-compliance-diagnostic/app/render-dashboard.js',
  './ontology-compliance-diagnostic/app/render-edit-session.js',
  './ontology-compliance-diagnostic/app/render-measures.js',
  './ontology-compliance-diagnostic/app/render-nlp-qa.js',
  './ontology-compliance-diagnostic/app/render-ontology.js',
  './ontology-compliance-diagnostic/app/render-resources.js',
  './ontology-compliance-diagnostic/app/render-standards.js',
  './ontology-compliance-diagnostic/app/report-export.js',
  './ontology-compliance-diagnostic/app/report-model.js',
  './ontology-compliance-diagnostic/app/scope-filter.js',
  './ontology-compliance-diagnostic/app/shared.js',
  './ontology-compliance-diagnostic/app/storage.js',
  './ontology-compliance-diagnostic/app/types.js',
  './ontology-compliance-diagnostic/editable-curation-workstream.md',
  './ontology-compliance-diagnostic/favicon.ico',
  './ontology-compliance-diagnostic/favicon.svg',
  './ontology-compliance-diagnostic/foundry-policy-graph/foundry-conformance-Screenshot 2026-03-20 000802.png',
  './ontology-compliance-diagnostic/foundry-policy-graph/foundry-conformity-graph.ttl',
  './ontology-compliance-diagnostic/foundry-policy-graph/processing-a-ontology.md',
  './ontology-compliance-diagnostic/index.html',
  './ontology-compliance-diagnostic/mermaid/notional-policy-model.mmd',
  './ontology-compliance-diagnostic/nlp-quality-assurance.html',
  './ontology-compliance-diagnostic/ontology-measures.html',
  './ontology-compliance-diagnostic/plans/spelling-and-grammar-checker.md',
  './ontology-compliance-diagnostic/queries/manifest.json',
  './ontology-compliance-diagnostic/queries/optional-manifest.js',
  './ontology-compliance-diagnostic/queries/q_annotationproperty-missing-rdfs-label.rq',
  './ontology-compliance-diagnostic/queries/q_annotationproperty-missing-skos-definition.rq',
  './ontology-compliance-diagnostic/queries/q_avoidPunning_ask.rq',
  './ontology-compliance-diagnostic/queries/q_class-has-parent-but-definition-not-aristotelian.rq',
  './ontology-compliance-diagnostic/queries/q_class-missing-cco-iscuratedinontology.rq',
  './ontology-compliance-diagnostic/queries/q_class-missing-parent-path-to-bfo.rq',
  './ontology-compliance-diagnostic/queries/q_class-missing-rdfs-label.rq',
  './ontology-compliance-diagnostic/queries/q_class-missing-skos-definition.rq',
  './ontology-compliance-diagnostic/queries/q_class-missing-skos-example.rq',
  './ontology-compliance-diagnostic/queries/q_class-missing-subclassof.rq',
  './ontology-compliance-diagnostic/queries/q_dataproperty-missing-rdfs-label.rq',
  './ontology-compliance-diagnostic/queries/q_dataproperty-missing-skos-definition.rq',
  './ontology-compliance-diagnostic/queries/q_datatypeproperty-missing-rdfs-domain.rq',
  './ontology-compliance-diagnostic/queries/q_datatypeproperty-missing-rdfs-label.rq',
  './ontology-compliance-diagnostic/queries/q_datatypeproperty-missing-rdfs-range.rq',
  './ontology-compliance-diagnostic/queries/q_datatypeproperty-missing-skos-definition.rq',
  './ontology-compliance-diagnostic/queries/q_duplicateLabels.rq',
  './ontology-compliance-diagnostic/queries/q_namedindividual-missing-rdfs-label.rq',
  './ontology-compliance-diagnostic/queries/q_namedindividual-missing-skos-definition.rq',
  './ontology-compliance-diagnostic/queries/q_objectproperty-missing-rdfs-domain.rq',
  './ontology-compliance-diagnostic/queries/q_objectproperty-missing-rdfs-label.rq',
  './ontology-compliance-diagnostic/queries/q_objectproperty-missing-rdfs-range.rq',
  './ontology-compliance-diagnostic/queries/q_objectproperty-missing-skos-definition.rq',
  './ontology-compliance-diagnostic/queries/q_onlyLabel.rq',
  './ontology-compliance-diagnostic/queries/q_ontology-has-cc0-or-ccby3-or-higher.rq',
  './ontology-compliance-diagnostic/queries/q_ontology-has-cc0-or-ccby4-license.rq',
  './ontology-compliance-diagnostic/queries/q_ontology-has-dcterms-accessRights.rq',
  './ontology-compliance-diagnostic/queries/q_ontology-has-dcterms-license-but-missing-cc0-or-ccby3-or-higher-URL.rq',
  './ontology-compliance-diagnostic/queries/q_ontology-has-dcterms-license-but-missing-cc0-or-ccby3-or-higher.rq',
  './ontology-compliance-diagnostic/queries/q_ontology-has-dcterms-license-but-not-cc0-or-ccby4-license.rq',
  './ontology-compliance-diagnostic/queries/q_ontology-has-dcterms-license-with-cc0-or-ccby3-or-higher-URL.rq',
  './ontology-compliance-diagnostic/queries/q_ontology-has-dcterms-license.rq',
  './ontology-compliance-diagnostic/queries/q_ontology-has-versioninfo-but-missing-date-or-semantic-versioning.rq',
  './ontology-compliance-diagnostic/queries/q_ontology-has-versioninfo.rq',
  './ontology-compliance-diagnostic/queries/q_ontology-has-versioniri-and-date-or-semantic-versioning.rq',
  './ontology-compliance-diagnostic/queries/q_ontology-has-versioniri-and-info-but-mismatch-versioning.rq',
  './ontology-compliance-diagnostic/queries/q_ontology-has-versioniri-and-valid-iri.rq',
  './ontology-compliance-diagnostic/queries/q_ontology-has-versioniri-but-has-no-valid-iri.rq',
  './ontology-compliance-diagnostic/queries/q_ontology-has-versioniri-but-missing-date-or-semantic-versioning.rq',
  './ontology-compliance-diagnostic/queries/q_ontology-has-versioniri-with-iso-8601-date.rq',
  './ontology-compliance-diagnostic/queries/q_ontology-has-versioniri.rq',
  './ontology-compliance-diagnostic/queries/q_ontology-missing-versioniri.rq',
  './ontology-compliance-diagnostic/queries/q_resource-missing-rdf-type.rq',
  './ontology-compliance-diagnostic/queries/standards-manifest.json',
  './ontology-compliance-diagnostic/styles/ontology-compliance-diagnostic.css',
  './ontology-tabulator/',
  './ontology-tabulator/app/core.js',
  './ontology-tabulator/app/main.js',
  './ontology-tabulator/app/ui-helpers.js',
  './ontology-tabulator/images/ontology-tabulator-alt.svg',
  './ontology-tabulator/index.html',
  './ontology-tabulator/styles/ontology-tabulator.css',
  './sparql-pattern-visualizer/',
  './sparql-pattern-visualizer/app/constants.js',
  './sparql-pattern-visualizer/app/log.js',
  './sparql-pattern-visualizer/app/ui_app.js',
  './sparql-pattern-visualizer/app/ui_toast.js',
  './sparql-pattern-visualizer/images/default-logo-uncropped.png',
  './sparql-pattern-visualizer/index.html',
  './sparql-pattern-visualizer/styles/sviz.css',
  './docxhund/',
  './docxhund/examples/example-docx-parsing.ttl',
  './docxhund/images/docxhund-base.png',
  './docxhund/index.html',
  './docxhund/scripts/config.js',
  './docxhund/scripts/docx-reader.js',
  './docxhund/scripts/docxhund-main.js',
  './docxhund/scripts/parser.js',
  './docxhund/scripts/rdf-writer.js',
  './docxhund/scripts/ui.js',
  './docxhund/scripts/utils.js',
  './docxhund/styles/docxhund-app.css',
  './table-nova/',
  './table-nova/app/metadataDrafts.js',
  './table-nova/app/rdf/buildDataset.js',
  './table-nova/app/rdf/ontology.js',
  './table-nova/app/rdf/schema.js',
  './table-nova/app/rdf/serialize.js',
  './table-nova/app/state/defaults.js',
  './table-nova/app/state/types.js',
  './table-nova/app/storage/indexedDb.js',
  './table-nova/app/table-nova.js',
  './table-nova/app/tabular/parseTabular.js',
  './table-nova/app/ui/render.js',
  './table-nova/app/ui/telemetry.js',
  './table-nova/images/logo-001.svg',
  './table-nova/index.html',
  './table-nova/styles/table-nova.css',
  './vendor/compromise_v14.15.1.js',
  './visual-lynx/',
  './visual-lynx/app/jsonld-visualizer-core.js',
  './visual-lynx/app/jsonld-visualizer-loader.js',
  './visual-lynx/app/jsonld-visualizer-ui.js',
  './visual-lynx/app/linked-data-transformer-core.js',
  './visual-lynx/app/linked-data-transformer-functions.js',
  './visual-lynx/app/linked-data-transformer-jest.js',
  './visual-lynx/app/linked-data-transformer-main.js',
  './visual-lynx/app/linked-data-transformer-registry.js',
  './visual-lynx/app/n3-sugar-serial.js',
  './visual-lynx/app/rdflib-sugar-serial.js',
  './visual-lynx/app/visual-lynx-cytoscape.js',
  './visual-lynx/data/bfo-json-ld.json',
  './visual-lynx/images/visual-lynx-bnw.svg',
  './visual-lynx/index.html',
  './visual-lynx/linked-data-transformer.html',
  './visual-lynx/rdf-serialization-prettifier.md',
  './visual-lynx/styles/cytoscape-visualizer.css',
  './visual-lynx/styles/d3-visualizer.css',
  './visual-lynx/styles/linked-data-transformer.css',
  './visual-lynx/visual-lynx-cytoscape.html',
];

// Single consolidated dataset produced by Python
const DATA_ASSETS = [
  './data/graph.jsonld',
  './data/ontology-registry.json',
];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const shell = await caches.open(CACHE_SHELL);
    await shell.addAll(SHELL_ASSETS);

    const data = await caches.open(CACHE_DATA);
    await data.addAll(DATA_ASSETS);

    self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(
      keys
        .filter((k) => ![CACHE_SHELL, CACHE_DATA].includes(k))
        .map((k) => caches.delete(k))
    );

    self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  const url = new URL(req.url);

  // Only same-origin GET requests
  if (req.method !== 'GET' || url.origin !== self.location.origin) return;

  const path = url.pathname;

  // Dataset: stale-while-revalidate
  if (path.endsWith('/data/graph.jsonld') || path.endsWith('/data/ontology-registry.json')) {
    event.respondWith(staleWhileRevalidate(req, CACHE_DATA));
    return;
  }

  // Everything else: network-first
  event.respondWith(networkFirst(req, CACHE_SHELL));
});

async function networkFirst(req, cacheName) {
  const cache = await caches.open(cacheName);

  try {
    const res = await fetch(req);
    if (res && res.ok) {
      await cache.put(req, res.clone());
    }
    return res;
  } catch (err) {
    const hit = await cache.match(req);
    if (hit) return hit;
    return new Response('Offline', { status: 503 });
  }
}

async function staleWhileRevalidate(req, cacheName) {
  const cache = await caches.open(cacheName);
  const hit = await cache.match(req);

  const fetchPromise = fetch(req)
    .then(async (res) => {
      if (res && res.ok) {
        await cache.put(req, res.clone());
      }
      return res;
    })
    .catch(() => null);

  return hit || (await fetchPromise) || new Response('Offline', { status: 503 });
}

self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') self.skipWaiting();
});
