PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?resource ?label ?curatedIn ?value ?violation
WHERE {
    VALUES ?punType { owl:Class owl:ObjectProperty owl:DatatypeProperty }
    ?resource a owl:NamedIndividual , ?punType .

    OPTIONAL {?resource rdfs:label ?label }
    OPTIONAL {?resource cco:is_curated_in_ontology ?curatedIn }

    BIND("Ontology element is a pun: it is treated as an individual and as a universal." as ?violation)
    BIND(?punType as ?value)

    }
    GROUP BY ?resource ?label ?curatedIn ?value ?violation
