### Range Inference Query
# infers range relationships in an ontology.
# It finds all properties that have a range defined and infers the range for the property.

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

INSERT {
      ?y rdf:type ?range .
      }
WHERE {
      ?x ?p ?y .
      ?p rdfs:range ?range .
     }